version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app # ローカルとコンテナ内の同期
    working_dir: /usr/src/app/20th-synthesizers-gallery
    command: yarn start
    ports:
      - "3000:3000"
    stdin_open: true # https://teratail.com/questions/249875
